# Generated by Django 5.1.7 on 2025-03-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('coremp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('nombre_facturacion', models.CharField(max_length=100)),
                ('direccion_facturacion', models.TextField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.registropublico')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coremp.plan')),
            ],
        ),
    ]
